### ISSUE TITLE
Add a wiki and links to wiki

### ISSUE THREAD

**Issue by westonbelk** [CUCyber/cucyber.github.io#17]
Wiki should be at https://github.com/cucyber/wiki

Link should probably  be under resources.

I don't know what kind of information is going in here.

**Comment by nbulischeck** [comment]
Wiki information is generally going to be the stuff discussed in #15

**Comment by lilyinstarlight** [comment]
I think I'll probably use VimWiki since I personally use that. It'll generate to pages in https://cucyber.net/wiki/ which should have links to GitHub for editing a given page, looking at history, or looking at the blame.

I think this could substitute #15 if we want. Shall I close that ticket @nbulischeck ?

**Comment by nbulischeck** [comment]
@fkmclane You can close #15  as long as we have a good idea of what is going into this.

**Comment by lilyinstarlight** [comment]
I'll leave it up for now until this has substituted #15.
