### ISSUE TITLE
Add achievements before 2016

### ISSUE THREAD

**Issue by westonbelk** [CUCyber/cucyber.github.io#19]
https://cucyber.net/about.html

* SECCDC
* PCDC
* PDFC

**Comment by westonbelk** [comment]
Closed

**Comment by nbulischeck** [comment]
Is there any reason the achievements for prior years were removed?

**Comment by nbulischeck** [comment]
We need to talk to Kevin McKenzie and friends to find out who was on the winning team for 2013, 2014, and 2015.

OR

We just leave it off

**Comment by klsimps** [comment]
We can just leave it off until we talk to him.

**Comment by nbulischeck** [comment]
Bump ^

**Comment by lilyinstarlight** [comment]
Here's what needs to be added -- I'll have to hope John knows who the team members were:

SECCDC 2012 - Qualified/Competed (this may be left out because idk if they still did qualifiers at the time because number of teams for SECCDC seems variable until 2013)
SECCDC 2013 - Best in Defense
PCDC 2013 - 1st Place
PCDC 2014 - 1st Place

As far as I know, that's everything since Clemson started competing in cybersecurity competitions since 2012.
