### ISSUE TITLE
Script Source Inconsistency

### ISSUE THREAD

**Issue by cyntheticfox** [CUCyber/cucyber.github.io#35]
Some scripts are sourced locally such as wow js: `/js/wow.min.js`, but others are remote, such as fontawesome: `http://kit.fontawesome.com/8f683739d8.js`.

Either they should be local or CDN-based, rather than a mix, especially if they aren't uniquely modified.

**Comment by lilyinstarlight** [comment]
https://cdn-src.dev.cucyber.net/

I upgraded some libraries to versions that are in CDNs which seems to have made the animations a little more pronounced. This might be how they were supposed to look and the wow.js we were using had bugs. If we want more subtle animations, we can adjust the `data-wow` attributes.

As state in the commit message, Modernizr was kept around due to it having custom settings and Modernizr not seeming to publish a CDN build, Ionicons was dropped after converting the one single icon used from it to FontAwesome, and html5shiv has been dropped because that's only active on IE8 and below.

**Comment by cyntheticfox** [comment]
It sounds like a good idea to use cdns, but if we're going to do so, we should implement SRI as well

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

I'd be happy to though
